### ISSUE TITLE
About documentation

### ISSUE THREAD

**Issue by rlacjfjin** [mahdims/3D-bin-packing#1]
Hi,
Is the documentation incomplete? 
Emmm...
There is no GA part description....
Or if you have published paper, could you tell me the paper's title?

Thanks,

**Comment by Gangstart** [comment]
朋友，你找到这个遗传算法原理描述的文章了吗？期待您的回复！

**Comment by mahdims** [comment]
Unfortunately, there is no documentation on the method. You can find the problem description and assumptions in the repo. 
Methods are straightforward use of Tabu search and GA.
