### ISSUE TITLE
About the experients results

### ISSUE THREAD

**Issue by Gangstart** [mahdims/3D-bin-packing#2]
Dear author:
         I ran the code in my computer, and the datasets are wtpack and BR respectively. However, the results were all worse than the paper of Liu etc.(2011), especially on the strongly heterogeneous problems, which don't match the conclusions of your documents. Is there something wrong with the code or me?  Which parts do I need to improve in order to get the better results? Expecting your reply!

**Comment by mahdims** [comment]
Hello, 
There are several reasons for your observation, 
- Additional consideration in our problem. Note that we account for placement based on the items delivery order. This means the results you obtain from this implementation is not comparable with Liu et al (2011).  (More constraints -> same or worse results)
- The stopping criteria and other algorithm parameters have a huge impact on the performance of the algorithm . I didn't properly tune the parameters for the given datasets.  
- This implementation is in Python and Liu eta l (2011) is in C++. We generally expect that C++ would be much faster than Python, thus given the same execution time limit, the solution provided by a C++ implementation has a better change to have a better quality. 
All in all, to say which method perform better, first we need to tackle the above issues, which was not the aim of this project. We only claim that the proposed approach is better in the sense it can handle additional realistic constraints.

**Comment by Gangstart** [comment]
Thanks for your reply! And there is another question. It seems to be no GA part description. Are there any detailed information for the GA part? Expecting for your reply!

> Hello, There are several reasons for your observation,
> 
> * Additional consideration in our problem. Note that we account for placement based on the items delivery order. This means the results you obtain from this implementation is not comparable with Liu et al (2011).  (More constraints -> same or worse results)
> * The stopping criteria and other algorithm parameters have a huge impact on the performance of the algorithm . I didn't properly tune the parameters for the given datasets.
> * This implementation is in Python and Liu eta l (2011) is in C++. We generally expect that C++ would be much faster than Python, thus given the same execution time limit, the solution provided by a C++ implementation has a better change to have a better quality.
>   All in all, to say which method perform better, first we need to tackle the above issues, which was not the aim of this project. We only claim that the proposed approach is better in the sense it can handle additional realistic constraints.
